# This Dockerfile is designed for local development only

FROM java:alpine

WORKDIR /wiremock
COPY wiremock.jar .
VOLUME /wiremock/data

CMD java -jar wiremock.jar --root-dir data --port=${WIREMOCK_PORT} --verbose
